# 定义 stages
stages:
  - build_imx6

# 定义 job
job1:
  stage: build_imx6
  tags: 
    - image-builder-20210223

  script:
    - source env/ci_imx6.sh && echo "123$FIRE_BOARD" && echo "laoyening/r/n" | make DOWNLOAD_MIRROR=china