#!/bin/bash

unset FIRE_BOARD
unset LINUX
unset UBOOT
unset DISTRIBUTION
unset DISTRIB_RELEASE
unset DISTRIB_TYPE
unset DISTRIB_ARCH
unset INSTALL_TYPE

FIRE_BOARD=ebf_imx_6ull_pro
LINUX=4.19.35
UBOOT=2020.10
DISTRIBUTION=Debian
DISTRIB_RELEASE=buster
DISTRIB_TYPE=console
DISTRIB_ARCH=armhf
INSTALL_TYPE=ALL
